# Generated by Django 2.2.7 on 2019-11-14 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('reason', models.IntegerField(choices=[(1, 'Vacation'), (2, 'Training'), (3, 'Work Travel'), (4, 'FMLA'), (5, 'Development'), (6, 'Other')], default=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.Person')),
            ],
        ),
    ]
