# Generated by Django 2.2.7 on 2019-11-15 02:49

from django.db import migrations, models


def default_setting(apps, schema_editor):
    AdminSetting = apps.get_model('core', 'AdminSetting')
    AdminSetting.objects.update_or_create(id=1, defaults={'max_out': 1})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('max_out', models.IntegerField(default=1)),
            ],
        ),
        migrations.RunPython(default_setting),
    ]
